version: "3"
services:
  frontend:
    build: ./frontend

  backend:
    build: ./backend
    ports:
      - "8000:5000"
    volumes:
      - .:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: "elasticsearch"
    ports:
      - 9200:9200
      - 9300:9300
